server:
  port: 8881

person:
  user: user
  password: 123
  age: 44
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cookbook?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  #Redis相关配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    expire: 60000
  jackson:
    date-format: yyyy-MM-dd
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.jxnu.entity

  time-zone: Asia/Shanghai
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  devtools:
    livereload:
      port: 35731
logging:
  level:
    com:
      jxnu:
        dao=debug: debug

#全局逻辑删除配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

